[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false
skip-idl = true

[programs.devnet]
pump = "C1NYLjRoFHPvBASeiWsFqFmWFcoFwzPYGKHCAiU86HAd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
